---
# Source: crossplane/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane
  labels:
    app: crossplane
    chart: crossplane-1.4.1
    release: crossplane
    heritage: Helm
imagePullSecrets:
- name: dockerhub
